#!/usr/bin/env python3
"""
session_start.py - SessionStart hook
Injects the decision log into CLAUDE.md at session start
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path


def get_project_root() -> Path:
    """Return the project root where CLAUDE.md exists"""
    # The hook is executed with the project root as cwd
    cwd = Path(os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd()))
    return cwd


def load_decisions(context_dir: Path) -> dict:
    """Load decisions.json"""
    decisions_file = context_dir / "decisions.json"
    if not decisions_file.exists():
        return {"version": "1.0.0", "last_updated": None, "decisions": []}
    try:
        with open(decisions_file, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return {"version": "1.0.0", "last_updated": None, "decisions": []}


def load_context_summary(context_dir: Path) -> str:
    """Load context_summary.md"""
    summary_file = context_dir / "context_summary.md"
    if not summary_file.exists():
        return ""
    try:
        with open(summary_file, "r", encoding="utf-8") as f:
            return f.read()
    except IOError:
        return ""


def format_decisions_for_context(decisions_data: dict) -> str:
    """Format decision data as text for CLAUDE.md"""
    decisions = decisions_data.get("decisions", [])
    if not decisions:
        return "_(No decisions recorded)_"

    # Prioritize active decisions, up to the latest 20
    active = [d for d in decisions if d.get("status") == "active"]
    superseded = [d for d in decisions if d.get("status") == "superseded"]

    lines = []

    if active:
        lines.append("### Active Decisions")
        for d in active[-20:]:
            v = d.get("version", "v?")
            ts = d.get("timestamp", "")[:10] if d.get("timestamp") else ""
            category = d.get("category", "general")
            title = d.get("title", "")
            content = d.get("content", "")
            lines.append(f"- **[{v}]** `{category}` {title} _{ts}_")
            if content:
                lines.append(f"  > {content}")

    if superseded:
        lines.append("\n### Superseded Decisions (Reference)")
        for d in superseded[-5:]:
            v = d.get("version", "v?")
            ts = d.get("timestamp", "")[:10] if d.get("timestamp") else ""
            title = d.get("title", "")
            lines.append(f"- ~~[{v}]~~ {title} _{ts}_")

    return "\n".join(lines)


def update_claude_md(project_root: Path, decisions_data: dict, summary: str):
    """Update the decision section in CLAUDE.md"""
    claude_md = project_root / "CLAUDE.md"

    # Load existing CLAUDE.md
    existing_content = ""
    if claude_md.exists():
        with open(claude_md, "r", encoding="utf-8") as f:
            existing_content = f.read()

    # Managed section markers
    START_MARKER = "<!-- CONTEXT-OPTIMIZER:START -->"
    END_MARKER = "<!-- CONTEXT-OPTIMIZER:END -->"

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    decision_count = len([d for d in decisions_data.get("decisions", []) if d.get("status") == "active"])
    last_updated = decisions_data.get("last_updated", "none")

    decisions_text = format_decisions_for_context(decisions_data)

    injected_section = f"""{START_MARKER}
## Context Optimization - Auto-injected Section
> _Last updated: {now} | Active decisions: {decision_count}_
> _This section is auto-generated by session_start.py_

{decisions_text}

### Session Summary (Previous)
{summary if summary else "_(No summary)_"}
{END_MARKER}"""

    # Replace existing marker section or append to end
    if START_MARKER in existing_content and END_MARKER in existing_content:
        start_idx = existing_content.index(START_MARKER)
        end_idx = existing_content.index(END_MARKER) + len(END_MARKER)
        new_content = existing_content[:start_idx] + injected_section + existing_content[end_idx:]
    else:
        new_content = existing_content.rstrip() + "\n\n" + injected_section + "\n"

    with open(claude_md, "w", encoding="utf-8") as f:
        f.write(new_content)

    return decision_count


def main():
    # Read event data from stdin (passed from Claude Code)
    try:
        event_data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        event_data = {}

    project_root = get_project_root()
    context_dir = project_root / ".claude" / "context"
    context_dir.mkdir(parents=True, exist_ok=True)

    # Load data
    decisions_data = load_decisions(context_dir)
    summary = load_context_summary(context_dir)

    # Update CLAUDE.md
    count = update_claude_md(project_root, decisions_data, summary)

    # Inject additional context for Claude Code (additionalContext)
    session_id = event_data.get("session_id", "unknown")
    trigger = event_data.get("trigger", "startup")

    output = {
        "additionalContext": (
            f"[Context Optimizer] Session started (trigger={trigger})\n"
            f"Active decisions: {count}\n"
            f"Decision log injected into CLAUDE.md. "
            f"Please make sure to record any important design changes or policy decisions."
        )
    }
    print(json.dumps(output, ensure_ascii=False))


if __name__ == "__main__":
    main()
